import type { Metadata, Viewport } from "next";
import { Bebas_Neue, Fira_Code, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar/Navbar";
import LenisProvider from "@/components/animate/Lenis/LenisProvider";
import Footer from "@/components/layout/Footer/Footer";
import FloatingIcons from "@/components/animate/FloatingIcons/FloatingIcons";
import LoaderPortfolio from "@/components/animate/LoaderPortfolio/LoaderPortfolio";

const inter = Inter({
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const firaCode = Fira_Code({
  weight: ["400", "500", "600", "700"],
  style: ["normal"],
  subsets: ["latin"],
  variable: "--font-fira-code",
  display: "swap",
});

const bebasNeue = Bebas_Neue({
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
  variable: "--font-bebas-neue",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Portofolio Diego Da Silva Marques",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${firaCode.variable} ${bebasNeue.variable} antialiased`}
      >
        <LoaderPortfolio />
        <LenisProvider>
          <FloatingIcons />
          <Navbar />
          {children}
          <Footer />
        </LenisProvider>
      </body>
    </html>
  );
}
